// pages/index.tsx

import Header from "@/components/Header";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "reactstrap";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar01.png" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-3">
            O melhor jeito de comprar o que você ama!!!
          </h1>

          <Link href="/products">
            <Button color="dark" className="px-5 pb-2 mt-5">
              Conheça nossos produtos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  );
};

export default Home;
